### ISSUE TITLE
Email addresses not coming through to the Mad Mimi list

### ISSUE THREAD

**Issue by Neal-Ghoshal** [katzwebservices/Gravity-Forms-Mad-Mimi#4]
Someone asked this on the wordpress.org site:
Had a user report a problem which I narrowed down to a conflict btwn GF and GF Mad Mimi add-on. The users was provided the confirmation and thought there was an error in the submission. The submitted info is received however. But the user is left with a page and spinner waiting for completion. 

And I'm having the same problem. Is there a fix for this Zack. Would really appreciate it as it means that I can use mad Mimi. cheers, Neal

**Comment by mikezielonka** [comment]
Hi All.

The stable version is causing this stable error for me: [Thu Dec 05 18:30:30 2013] [error] [client 209.225.100.43] PHP Fatal error: Call to undefined method MadMimi_SuperClass::listSubscribe() in /nas/wp/www/cluster-1470/wholelifestyle/wp-content/plugins/gravity-forms-mad-mimi/madmimi.php on line 1171, referer: http://wholelifestylenutrition.com/giveaways/1000-amazon-gift-card/

Mike

**Comment by mikezielonka** [comment]
Switch to beta and it will work for you guys.  :)

**Comment by Neal-Ghoshal** [comment]
Hi Mike - thanks for the message. The thing about using the beta version is that that version removes the Mad Mimi link under forms so that I cannot add any Mad Mimi links.

I do have a right up to date Wordpress, all plugins, at a great Genesis theme so it can't be one of those. A bug in this Mad Mimi plugin?

**Comment by zackkatz** [comment]
You add the Feeds under “Form Settings” with the beta.

**Comment by Neal-Ghoshal** [comment]
Hi Zack - many thanks for that - I see that now. However I tested that and tried a feed to one of my lists and it hasn't added the contact.

I do know what I'm doing because i used this on another site and it was working fine (though I haven't checked in the last couple of months whether it is adding contacts OK still. 

I have a similar set up with mailchimp and that one is working well. I'd just prefer to use Mad Mimi

Any ideas?

**Comment by mikezielonka** [comment]
Not sure what to caused stable to stop working or how long it was down ( I
should check the error log).  We just re imported the 2 results from 2
forms to ensure things no one is missed.

I like the beta UX a lot more to.  I hope it goes live soon @zackkatz

Mike

Mike Zielonka
Mobile:  (414) 350-0060
Email:    mikezielonka@gmail.com
@mikezielonka http://twitter.com/mikezielonka

**Comment by Neal-Ghoshal** [comment]
Hi Mike and Zack - thanks for your replies.

I've tried the Beta and the Stable and neither are adding contacts to my list.

Now I've checked another website, the first one where I used this plugin - it was adding the contacts very nicely for a few months - I have a number of feeds set up so each email address gets added to anything from one to 8 lists depending on what the user submits.

That's all been working fine. But sometime around 21 October that stopped working - and now all the users who have signed up since then will now need to be added manually to each list - massive time consuming effort!

What happened around mid October - some sort of update to the stable version which meant it didn't work any more?

On the new site I'm trying this plugin to work neither the stable nor the beta version actually adds the contacts to my Mad Mimi list.

This makes the plugin simply not worth it and I'm seriously now looking to transfer everything over to Mailchimp which I'd rather not do.

Could this plugin be fixed? Please do help. Much appreciated if you can and will donate if it is.

Many thanks - Neal

**Comment by Soupie4** [comment]
Hi Mike, Zack and others in this thread. :)

I am having the same problem - though my needs are less complex than those of others here. (To date we have only one Mad Mimi list for our newsletter.). 

Fortunately I do get the email notifications from the sign up form, but (like Neal) I am reduced to updating manually in Mad Mimi which defeats the purpose really!

At present I'm using the stable plugin, rather than the beta. But switching between the two made no difference - neither is sending any information at all to Mad Mimi. I also am unable to delete the beta plugin because deleting it will apparently delete both.

I look forward to a fix for this - or I assume I'll have to uninstall the plugin and revert to Mad Mimi's webforms instead. I would prefer not to do that, as I'd like to continue using Gravity Forms if possible.

And, as Neal has also said, I will be more than happy t donate if the plugin can be fixed and iit becomes usable! :)

Many thanks
Sue

**Comment by zackkatz** [comment]
This should be fixed in 2.0.1 - sorry for the problems.

**Comment by Soupie4** [comment]
Hi Zack

Many thanks for letting me know. :)

Cheers
Sue
